### ISSUE TITLE
Private Messages may cause an infinite loop

### ISSUE THREAD

**Issue by maxaudron** [nihilist-space/circ#35]
When sending a PM to circ there is a potential for an endless loop.
This is caused by us taking the first argument of the IRC Raw Message as a return address, which is correct for channels but not for PMs.

A PM Message
```
:audron!audron@user/audron PRIVMSG circ :%ping
                                    ^ we use this argument
```

We will need to implement a check for if this argument is our own name, and if it is we need to use the prefix to send the reply

**Comment by pta2002** [comment]
I can work on this today, doesn't look like a big issue
